# Arquivo de configuração para o Nixpacks (builder do Railway)

# --- Fase de Instalação ---
[phases.setup]
# Lista de pacotes para instalar no ambiente.
# Isso garante que o SDK do .NET 8 esteja disponível.
nixPkgs = ["dotnet-sdk_8"]

# --- Fase de Build ---
[build]
# Comando exato para construir o projeto, evitando erros com o .sln
cmd = "dotnet publish API/vitalapi/vitalapi.csproj -c Release -o out"

# --- Fase de Execução ---
[start]
# Comando para iniciar a aplicação depois do deploy
cmd = "./out/vitalapi"